acronyms = {
    "A": "Amber",
    "AAA": "Amended meteorological message",
    "A/A": "Air-to-air",
    "A/G": "Air-to-ground",
    "AAD": "Assigned altitude deviation",
    "AAIM": "Aircraft autonomous integrity monitoring",
    "AAL": "Above aerodrome level",
    "ABI": "Advance boundary information",
    "ABM": "Abeam",
    "ABN": "Aerodrome beacon",
    "ABT": "About",
    "ABV": "Above",
    "AC": "Altocumulus",
    "ACARS": "Aircraft communication addressing and reporting system",
    "ACAS": "Airborne collision avoidance system",
    "ACC": "Area control centre",
    "ACCID": "Notification of an aircraft accident",
    "ACFT": "Aircraft",
    "ACK": "Acknowledge",
    "ACL": "Altimeter check location",
    "ACN": "Aircraft classification number",
    "ACP": "Acceptance ",
    "ACPT": "Accept",
    "ACT": "Active",
    "AD": "Aerodrome",
    "ADA": "Advisory area",
    "ADC": "Aerodrome chart",
    "ADDN": "Addition",
    "ADF": "Automatic direction-finding equipment",
    "ADIZ": "Air defence identification zone",
    "ADJ": "Adjacent",
    "ADO": "Aerodrome office ",
    "ALERFA": "Alert phase",
    "ALR": "Alerting ",
    "ALRS": "Alerting service",
    "ALS": "Approach lighting system",
    "ALT": "Altitude",
    "ALTN": "Alternate",
    "ALTN": "Alternate ",
    "AMA": "Area minimum altitude",
    "AMD": "Amend",
    "AMDT": "Amendment ",
    "AMS": "Aeronautical mobile service",
    "AMSL": "Above mean sea level",
    "AMSS": "Aeronautical mobile satellite service",
    "ANC...": "Aeronautical chart — 1:500 000 ",
    "ANCS...": "Aeronautical navigation chart — small scale ",
    "ANS": "Answer",
    "AOC...": "Aerodrome obstacle chart ",
    "AP": "Airport ",
    "APAPI": "Abbreviated precision approach path indicator",
    "APCH": "Approach",
    "APDC...": "Aircraft parking/docking chart ",
    "APN": "Apron",
    "APP": "Approach control office",
    "APR": "April",
    "APRX": "Approximate",
    "APSG": "After passing",
    "APV": "Approve",
    "ARC": "Area chart",
    "ARNG": "Arrange",
    "ARO": "Air traffic services reporting office",
    "ARP": "Aerodrome reference point",
    "ARP": "Air-report ",
    "ARQ": "Automatic error correction",
    "ARR": "Arrival ",
    "ARR": "Arrive",
    "ARS": "Special air-report ",
    "ARST": "Arresting ",
    # "AS": "Altostratus",
    "ASC": "Ascend to",
    "ASDA": "Accelerate-stop distance available",
    "ASE": "Altimetry system error",
    "ASHTAM": "Special series NOTAM notifying, by means of a specific format, change in activity of a volcano, a volcanic eruption and/or volcanic ash cloud that is of significance to aircraft operations",
    "ASPH": "Asphalt",
    "AT...": "At ",
    "ATA": "Actual time of arrival",
    "ATC": "Air traffic control ",
    "ATCSMAC.": ". .        Air traffic control surveillance minimum altitude chart ",
    "ATD": "Actual time of departure",
    "ATFM": "Air traffic flow management",
    "ATIS": "Automatic terminal information service",
    "ATM": "Air traffic management",
    "ATN": "Aeronautical telecommunication network",
    "ATP...": "At . . . ",
    "ATS": "Air traffic services",
    "ATTN": "Attention ",
    "AT-VASIS": "Abbreviated T visual approach slope indicator system",
    "ATZ": "Aerodrome traffic zone",
    "AUG": "August",
    "AUTH": "Authorized",
    "AUW": "All up weight",
    "AUX": "Auxiliary",
    "AVBL": "Available",
    "AVG": "Average",
    "AVGAS": "Aviation gasoline",
    "AWTA": "Advise at what time able",
    "AWY": "Airway",
    "AZM": "Azimuth",
    "B": "Blue",
    "BA": "Braking action  ",
    "BARO-VNAV": "Barometric vertical navigation",
    "BASE": "Cloud base",
    "BCFG": "Fog patches",
    "BCN": "Beacon ",
    "BCST": "Broadcast",
    "BDRY": "Boundary",
    "BECMG": "Becoming",
    "BFR": "Before",
    "BKN": "Broken",
    "BL...": "Blowing ",
    "BLDG": "Building",
    "BLO": "Below clouds",
    "BLW...": "Below . . .",
    "BOMB": "Bombing",
    "BR": "Mist",
    "BRF": "Short ",
    "BRG": "Bearing",
    "BRKG": "Braking",
    "BS": "Commercial broadcasting station",
    "BTL": "Between layers",
    "BTN": "Between",
    "BUFR": "Binary universal form for the representation of meteorological data",
    "...C": "Centre ",
    "C": "Degrees Celsius  ",
    "CA": "Course to an altitude",
    "CAT": "Category",
    "CAT": "Clear air turbulence",
    "CAVOK": " Visibility, cloud and present weather better than prescribed values",
    "CB": " Cumulonimbus",
    "CC": "Cirrocumulus",
    "CCA": "",
    "CD": "Candela",
    "CDN": "Coordination ",
    "CF": "Change frequency to . . .",
    "CF": "Course to a fix",
    "CFM*": "Confirm",
    "CGL": "Circling guidance light",
    "CH": "Channel",
    "CH#": "This is a channel-continuity-check of transmission to permit comparison of your record of channelsequence numbers of messages received on the channel ",
    "CHEM": "Chemical",
    "CHG": "Modification ",
    "CI": "Cirrus",
    "CIDIN": "Common ICAO data interchange network",
    "CIT": "Near",
    "CIV": "Civil",
    "CK": "Check",
    "CL": "Centre line",
    "CLA": "Clear type of ice formation",
    "CLBR": "Calibration",
    "CLD": "Cloud",
    "CLG": "Calling",
    "CLIMB-OUT": "Climb-out area",
    "CLR": "Clear",
    "CLRD": "Runway",
    "CLSD": "Close",
    "CM": "Centimetre",
    "CMB": "Climb to",
    "CMPL": "Completion",
    "CNL": "Cancel",
    "CNL": "Flight plan cancellation ",
    "CNS": "Communications, navigation and surveillance",
    "COM": "Communications",
    "CONC": "Concrete",
    "COND": "Condition",
    "CONS": "Continuous",
    "CONST": "Construction",
    "CONT": "Continue",
    "COOR": "Coordinate",
    "COORD": "Coordinates",
    "COP": "Change-over point",
    "COR": "Correct",
    "COT": "At the coast",
    "COV": "Cover",
    "CPDLC": "Controller-pilot data link communications",
    "CPL": "Current flight plan ",
    "CRC": "Cyclic redundancy check",
    "CRM": "Collision risk model",
    "CRZ": "Cruise",
    "CS": "Call sign",
    "CS": "Cirrostratus",
    "CTA": "Control area",
    "CTAM": "Climb to and maintain",
    "CTC": "Contact",
    "CTL": "Control",
    "CTN": "Caution",
    "CTR": "Control zone",
    "CU": "Cumulus",
    "CUF": "Cumuliform",
    "CUST": "Customs",
    "CVR": "Cockpit voice recorder",
    "CW": "Continuous wave",
    "CWY": "Clearway",
    "D": "Downward ",
    "D...": "Danger area ",
    "DA": "Decision altitude",
    "D-ATIS": " Data link automatic terminal information service",
    "DCD": "Double channel duplex",
    "DCKG": "Docking",
    "DCP": "Datum crossing point",
    "DCPC": "Direct controller-pilot communications",
    "DCS": "Double channel simplex",
    "DCT": "Direct ",
    "DE*": "From ",
    "DEC": "December",
    "DEG": "Degrees",
    "DEP": "Depart",
    "DEP": "Departure ",
    "DEPO": "Deposition",
    "DER": "Departure end of the runway",
    "DES": "Descend to",
    "DEST": "Destination",
    "DETRESFA": "Distress phase",
    "DEV": "Deviation",
    "DF": "Direction finding",
    "DFDR": "Digital flight data recorder",
    "DFTI": "Distance from touchdown indicator",
    "DH": "Decision height",
    "DIF": "Diffuse",
    "DIST": "Distance",
    "DIV": "Divert",
    "DLA": "Delay",
    "DLA": "Delay ",
    "DLIC": "Data link initiation capability",
    "DLY": "Daily",
    "DME": "Distance measuring equipment",
    "DNG": "Danger",
    "DOM": "Domestic",
    "DP": "Dew point temperature",
    "DPT": "Depth",
    "DR": "Dead reckoning",
    "DR...": "Low drifting ",
    "DRG": "During",
    "DS": "Duststorm",
    "DSB": "Double sideband",
    "DTAM": "Descend to and maintain",
    "DTG": "Date-time group",
    "DTHR": "Displaced runway threshold",
    "DTRT": "Deteriorate",
    "DTW": "Dual tandem wheels",
    "DU": "Dust",
    "DUC": "Dense upper cloud",
    "DUPE#": "This is a duplicate message ",
    "DUR": "Duration",
    "D-VOLMET": "Data link VOLMET",
    "DVOR": "Doppler VOR",
    "DW": "Dual wheels",
    "DZ": "Drizzle",
    "E": "East",
    "EAT": "Expected approach time",
    "EB": "Eastbound",
    "EDA": "Elevation differential area",
    "EEE#": "Error ",
    "EET": "Estimated elapsed time",
    "EFC": "Expect further clearance ",
    "EFIS": " Electronic flight instrument system",
    "EGNOS": " European geostationary navigation overlay service",
    "EHF": "Extremely high frequency [30 000 to 300 000 MHz]",
    "ELBA": "Emergency location beacon — aircraft",
    "ELEV": "Elevation",
    "ELR": "Extra long range",
    "ELT": "Emergency locator transmitter",
    "EM": "Emission",
    "EMBD": "Embedded in a layer ",
    "EMERG": "Emergency",
    "END": "Stop-end ",
    "ENE": "East-north-east",
    "ENG": "Engine",
    "ENR": "En route",
    "ENRC...": "Enroute chart ",
    "EOBT": "Estimated off-block time",
    "EQPT": "Equipment",
    "ER*": "Here . . .",
    "ESE": "East-south-east",
    "EST": "Estimate",
    "ETA*": "Estimated time of arrival",
    "ETD": "Estimated time of departure",
    "ETO": "Estimated time over significant point",
    "EUR": "RODEX           European regional OPMET data exchange",
    "EV": "Every",
    "EVS": "Enhanced vision system",
    "EXC": "Except",
    "EXER": "Exercises",
    "EXP": "Expect",
    "EXTD": "Extend",
    "F": "Fixed",
    "FA": "Course from a fix to an altitude",
    "FAC": "Facilities",
    "FAF": "Final approach fix",
    "FAL": "Facilitation of international air transport",
    "FAP": "Final approach point",
    "FAS": "Final approach segment",
    "FATO": "Final approach and take-off area",
    "FAX": "Facsimile transmission",
    "FBL": "Light ",
    "FC": "Funnel cloud ",
    "FCST": "Forecast",
    "FCT": "Friction coefficient",
    "FDPS": "Flight data processing system",
    "FEB": "February",
    "FEW": "Few",
    "FG": "Fog",
    "FIC": "Flight information centre",
    "FIR": "Flight information region",
    "FIS": "Flight information service",
    "FISA": "Automated flight information service",
    "FL": "Flight level",
    "FLD": "Field",
    "FLG": "Flashing",
    "FLR": "Flares",
    "FLT": "Flight",
    "FLTCK": "Flight check",
    "FLUC": "Fluctuating",
    "FLW": "Following",
    "FLY": "Fly",
    "FM": "Course from a fix to manual termination ",
    "FM": "From",
    "FM...": "From ",
    "FMC": "Flight management computer",
    "FMS": "Flight management system",
    "FMU": "Flow management unit",
    "FNA": "Final approach",
    "FPAP": "Flight path alignment point",
    "FPL": "Filed flight plan ",
    "FPM": "Feet per minute",
    "FPR": "Flight plan route",
    "FR": "Fuel remaining",
    "FREQ": "Frequency",
    "FRI": "Friday",
    "FRNG": "Firing",
    "FRONT": "Front ",
    "FROST": "Frost ",
    "FRQ": "Frequent",
    "FSL": "Full stop landing",
    "FSS": "Flight service station",
    "FST": "First",
    "FT": "Feet ",
    "FTE": "Flight technical error",
    "FTP": "Fictitious threshold point",
    "FTT": "Flight technical tolerance",
    "FU": "Smoke",
    "FZ": "Freezing",
    "FZDZ": "Freezing drizzle",
    "FZFG": "Freezing fog",
    "FZRA": "Freezing rain",
    "G": "Green",
    "G...": "Variations from the mean wind speed ",
    "GA": "Go ahead, resume sending ",
    "G/A": "Ground-to-air",
    "G/A/G": "Ground-to-air and air-to-ground",
    "GAGAN": "GPS and geostationary earth",
    "GAIN": "Airspeed",
    "GAMET": "Area forecast for low-level flights",
    "GARP": "GBAS azimuth reference point",
    "GBAS": " Ground-based augmentation system",
    "GCA": "Ground controlled approach system",
    "GEN": "General",
    "GEO": "Geographic",
    "GES": "Ground earth station",
    "GLD": "Glider",
    "GLONASS": " Global",
    "GLS": "GBAS landing system",
    "GMC...": "Ground movement chart ",
    "GND": "Ground",
    "GNDCK": "Ground check",
    "GNSS": "Global navigation satellite system",
    "GP": "Glide path",
    "GPA": "Glide path angle",
    "GPIP": "Glide path intercept point",
    "GPS": "Global positioning system",
    "GPWS": "Ground proximity warning system",
    "GR": "Hail",
    "GRAS": " Groundbased regional augmentation system",
    "GRASS": "Grass landing area",
    "GRIB": "Processed meteorological data in the form of grid point values expressed in binary form ",
    "GRVL": "Gravel",
    "GS": "Ground speed",
    "GS": "Small hail and/or snow pellets",
    "GUND": "Geoid undulation",
    "H": "High pressure area",
    "H24": "Continuous day and night service",
    "HA": "Holding/racetrack to an altitude",
    "HAPI": "Helicopter approach path indicator",
    "HBN": "Hazard beacon",
    "HDF": "High frequency direction-finding station",
    "HDG": "Heading",
    "HEL": "Helicopter",
    "HF": "High frequency [3 000 to 30 000 kHz]",
    "HF": "Holding/racetrack to a fix",
    "HGT": "Height",
    "HJ": "Sunrise to sunset",
    "HLDG": "Holding",
    "HM": "Holding/racetrack to a manual termination",
    "HN": "Sunset to sunrise",
    "HO": "Service available to meet operational requirements",
    "HOL": "Holiday",
    "HOSP": "Hospital aircraft",
    "HPA": "Hectopascal",
    "HR": "Hours",
    "HS": "Service available during hours of scheduled operations",
    "HUD": "Head-up display",
    "HURCN": "Hurricane",
    "HVDF": "High and very high frequency directionfinding stations ",
    "HVY": "Heavy",
    "HVY": "Heavy ",
    "HX": "No specific working hours",
    "HYR": "Higher",
    "HZ": "Haze",
    "HZ": "Hertz ",
    "IAC...": "Instrument approach chart ",
    "IAF": "Initial approach fix",
    "IAO": "In and out of clouds",
    "IAP": "Instrument approach procedure",
    "IAR": "Intersection of air routes",
    "IAS": "Indicated airspeed",
    "IBN": "Identification beacon",
    "IC": "Ice crystals ",
    "ICE": "Icing",
    "ID": "Identifier",
    "IDENT": "Identification",
    "IF": "Intermediate approach fix",
    "IFF": "Identification friend/foe",
    "IFR": "Instrument flight rules",
    "IGA": "International general aviation",
    "ILS": "Instrument landing system",
    "IM": "Inner marker",
    "IMC": "Instrument meteorological conditions",
    "IMG": "Immigration",
    "IMI*": "Interrogation sign ",
    "IMPR": "Improve",
    "IMT": "Immediate",
    "INA": "Initial approach",
    "INBD": "Inbound",
    "INC": "In cloud",
    "INCERFA": "Uncertainty phase",
    "INFO": "Information",
    "INOP": "Inoperative",
    "INP": "If not possible",
    "INPR": "In progress",
    "INS": "Inertial navigation system",
    "INSTL": "Install",
    "INSTR": "Instrument",
    "INT": "Intersection",
    "INTL": "International",
    "INTRG": "Interrogator",
    "INTRP": "Interrupt",
    "INTSF": "Intensify",
    "INTST": "Intensity",
    "IR": "Ice on runway",
    "IRS": "Inertial reference system",
    "ISA": "International standard atmosphere",
    "ISB": "Independent sideband",
    "ISOL": "Isolated",
    "JAN": "January",
    "JTST": "Jet stream",
    "JUL": "July",
    "JUN": "June",
    "KG": "kg",
    "KHZ": "KHz",
    "KIAS": "Knots indicated airspeed",
    "KM": "km",
    "KMH": "km/hw",
    "KPA": "Kilopascal",
    "KT": "Knots",
    "KW": "kW",
    "...L": "Left ",
    "L": "Locator ",
    "L": "Low pressure area",
    "LAM": "Logical acknowledgement ",
    "LAN": "Inland",
    "LAT": "Latitude",
    "LCA": "Local",
    "LDA": "Landing distance available",
    "LDAH": "Landing distance available, helicopter",
    "LDG": "Landing",
    "LDI": "Landing direction indicator",
    "LEN": "Length",
    "LF": "Low frequency [30 to 300 kHz]",
    "LGT": "Light",
    "LGTD": "Lighted",
    "LIH": "Light intensity high",
    "LIL": "Light intensity low",
    "LIM": "Light intensity medium",
    "LINE": "Line ",
    "LM": "Locator, middle",
    "LMT": "Local mean time",
    "LNAV": " Lateral navigation",
    "LNG": "Long ",
    "LO": "Locator, outer",
    "LOC": "Localizer",
    "LONG": "Longitude",
    "LORAN": "LORAN ",
    "LOSS": "Airspeed",
    "LPV": "Localizer performance with vertical guidance",
    "LR": "The last message received by me was . . .  ",
    "LRG": "Long range",
    "LS": "The last message sent by me was . . .",
    "LTD": "Limited",
    "LTP": "Landing threshold point",
    "LTT": "Landline teletypewriter",
    "LV": "Light and variable ",
    "LVE": "Leave",
    "LVL": "Level",
    "LVP": "Low visibility procedures",
    "LYR": "Layer",
    "...M": "Metres ",
    "M...": "Mach number ",
    "M...": "Minimum value of runway visual range ",
    "MAA": "Maximum authorized altitude",
    "MAG": "Magnetic",
    "MAHF": "Missed approach holding fix",
    "MAINT": "Maintenance",
    "MAP": "Aeronautical maps and charts",
    "MAPT": "Missed approach point",
    "MAR": "At sea",
    "MAR": "March",
    "MAS": "Manual Al simplex",
    "MATF": "Missed approach turning fix",
    "MAX": "Maximum",
    "MAY": "May",
    "MBST": "Microburst",
    "MCA": "Minimum crossing altitude",
    "MCW": "Modulated continuous wave",
    "MDA": "Minimum descent altitude",
    "MDF": "Medium frequency direction-finding station",
    "MDH": "Minimum descent height",
    "MEA": "Minimum en-route altitude",
    "MEHT": "Minimum eye height over threshold ",
    "MET": "Meteorological",
    "METAR": "Aerodrome routine meteorological report ",
    "MET": "REPORT          Local routine meteorological report ",
    "MF": "Medium frequency [300 to 3 000 kHz]",
    "MHDF": "Medium and high frequency directionfinding stations ",
    "MHVDF": "Medium, high and very high frequency direction-finding stations ",
    "MHZ": "Megahertz",
    "MID": "Mid-point ",
    "MIFG": "Shallow fog",
    "MIL": "Military",
    "MIN*": "Minutes",
    "MIS": "Missing . . . ",
    "MKR": "Marker radio beacon",
    "MLS": "Microwave landing system",
    "MM": "Middle marker",
    "MNM": "Minimum",
    "MNPS": "Minimum navigation performance specifications",
    "MNT": "Monitor",
    "MNTN": "Maintain",
    "MOA": "Military operating area",
    "MOC": "Minimum obstacle clearance ",
    "MOCA": "Minimum obstacle clearance altitude",
    "MOD": "Moderate ",
    "MON": "Above mountains",
    "MON": "Monday",
    "MOPS": "Minimum operational performance standards",
    "MOV": "Move",
    "MPS": "Metres per second",
    "MRA": "Minimum reception altitude",
    "MRG": "Medium range",
    "MRP": "ATS/MET reporting point",
    "MS": "Minus",
    "MSA": "Minimum sector altitude",
    "MSAS": " satellite-based augmentation system",
    "MSAW": "Minimum safe altitude warning",
    "MSG": "Message",
    "MSL": "Mean sea level",
    "MSR#": "Message . . . ",
    "MSSR": "Monopulse secondary surveillance radar",
    "MT": "Mountain",
    "MTU": "Metric units",
    "MTW": "Mountain waves",
    "MVDF": "Medium and very high frequency direction- finding stations ",
    "MWO": "Meteorological watch office",
    "MX": "Mixed type of ice formation ",
    "N": "No distinct tendency ",
    "N": "North",
    "NADP": "Noise abatement departure procedure",
    "NASC": "National AIS system centre",
    "NAT": "North Atlantic",
    "NAV": "Navigation",
    "NB": "Northbound",
    "NBFR": "Not before",
    "NC": "No change",
    "NCD": "No cloud detected ",
    "NDB": "Non-directional radio beacon",
    "NDV": "No directional variations available ",
    "NE": "North-east",
    "NEB": "North-eastbound",
    "NEG": "No",
    "NGT": "Night",
    "NIL*": "None",
    "NM": "Nautical miles",
    "NML": "Normal",
    "NN": "No name, unnamed",
    "NNE": "North-north-east",
    "NNW": "North-north-west",
    "NO": "No ",
    "NOF": "International NOTAM office",
    "NOSIG": "No significant change ",
    "NOTAM": "A notice distributed by means of telecommuni-cation containing information concerning the establishment, condition",
    "NOV": "November",
    "NOZ": "Normal operating zone",
    "NPA": "Non-precision approach",
    "NR": "Number",
    "NRH": "No reply heard",
    "NS": "Nimbostratus",
    "NSC": "Nil significant cloud",
    "NSE": "Navigation system error",
    "NSW": "Nil significant weather",
    "NTL": "National",
    "NTZ": "No transgression zone",
    "NW": "North-west",
    "NWB": "North-westbound",
    "NXT": "Next",
    "OAC": "Oceanic area control centre",
    "OAS": "Obstacle assessment surface",
    "OBS": "Observe",
    "OBSC": "Obscure",
    "OBST": "Obstacle",
    "OCA": "Obstacle clearance altitude",
    "OCA": "Oceanic control area",
    "OCC": "Occulting ",
    "OCH": "Obstacle clearance height",
    "OCNL": "Occasional",
    "OCS": "Obstacle clearance surface",
    "OCT": "October",
    "OFZ": "Obstacle free zone",
    "OGN": "Originate ",
    "OHD": "Overhead",
    "OIS": "Obstacle identification surface",
    "OK*": "We agree",
    "OLDI": "On-line data interchange",
    "OM": "Outer marker",
    "OPA": "Opaque, white type of ice formation",
    "OPC": "Control indicated is operational control",
    "OPMET": "Operational meteorological ",
    "OPN": "Open",
    "OPR": "Operator",
    "OPS": "Operations",
    "O/R": "On request",
    "ORD": "Order",
    "OSV": "Ocean station vessel",
    "OTP": "On top",
    "OTS": "Organized track system",
    "OUBD": "Outbound",
    "OVC": "Overcast",
    "P...": "Maximum value of wind speed",
    "P...": "Prohibited area ",
    "PA": "Precision approach",
    "PALS": "Precision approach lighting system ",
    "PANS": "Procedures for air navigation services",
    "PAPI": "Precision approach path indicator",
    "PAR": "Precision approach radar",
    "PARL": "Parallel",
    "PATC...": "Precision approach terrain chart ",
    "PAX": "Passenger",
    "PBN": "Performance-based navigation",
    "PCD": "Proceed",
    "PCL": "Pilot-controlled lighting",
    "PCN": "Pavement classification number",
    "PDC": "Pre-departure clearance",
    "PDG": "Procedure design gradient",
    "PER": "Performance",
    "PERM": "Permanent",
    "PIB": "Pre-flight information bulletin",
    "PJE": "Parachute jumping exercise",
    "PL": "Ice pellets",
    "PLA": "Practice low approach",
    "PLN": "Flight plan",
    "PLVL": "Present level",
    "PN": "Prior notice required",
    "PNR": "Point of no return",
    "PO": "Dust/sand whirls ",
    "POB": "Persons on board",
    "POSS": "Possible",
    "PPI": "Plan position indicator",
    "PPR": "Prior permission required",
    "PPSN": "Present position",
    "PRFG": "Aerodrome partially covered by fog",
    "PRI": "Primary",
    "PRKG": "Parking",
    "PROB": "Probability",
    "PROC": "Procedure",
    "PROV": "Provisional",
    "PRP": "Point-in-space reference point",
    "PS": "Plus",
    "PSG": "Passing",
    "PSN": "Position",
    "PSP": "Pierced steel plank",
    "PSR": "Primary surveillance radar",
    "PSYS": "Pressure system",
    "PTN": "Procedure turn",
    "PTS": "Polar track structure",
    "PWR": "Power",
    "QD": "Do you intend to ask me for a series of bearings?",
    "QDM": "Magnetic heading ",
    "QDR": "Magnetic bearing",
    "QFE": "Atmospheric pressure at aerodrome elevation ",
    "QFU": "Magnetic",
    "QGE": "What is my distance to your station?",
    "QJH": "Shall I run my test tape/a test sentence?",
    "QNH": "Altimeter sub-scale setting to obtain elevation when on the ground",
    "QSP": "Will you relay to . . . free of charge?",
    "QTA": "Shall I cancel telegram number . . .?",
    "QTE": "True bearing",
    "QTF": "Will you give me the position of my station according to the bearings taken by the D/F stations which you control? ",
    "QUAD": "Quadrant",
    "QUJ": "Will you indicate the TRUE track to reach you?",
    "...R": "Right ",
    "R": "Rate of turn",
    "R": "Red",
    "R...": "Restricted area ",
    "R...": "Runway ",
    "R*": "Received ",
    "RA": "Rain",
    "RA": "Resolution advisory",
    "RAC": "Rules of the air and air traffic services",
    "RAG": "Ragged",
    "RAG": "Runway arresting gear",
    "RAI": "Runway alignment indicator",
    "RAIM": "Receiver autonomous integrity monitoring",
    "RASC": "Regional AIS system centre",
    "RASS": "Remote altimeter setting source",
    "RB": "Rescue boat",
    "RCA": "Reach cruising altitude",
    "RCC": "Rescue coordination centre",
    "RCF": "Radiocommunication failure ",
    "RCH": "Reach",
    "RCL": "Runway centre line",
    "RCLL": "Runway centre line light",
    "RCLR": "Recleared",
    "RCP": "Required communication performance",
    "RDH": "Reference datum height",
    "RDL": "Radial",
    "RDO": "Radio",
    "RE": "Recent ",
    "REC": "Receive",
    "REDL": "Runway edge light",
    "REF": "Reference to . . .",
    "REG": "Registration",
    "RENL": "Runway end light",
    "REP": "Report",
    "REQ": "Request",
    "RERTE": "Re-route",
    "RESA": "Runway end safety area",
    "RF": "Constant radius arc to a fix",
    "RG": "Range ",
    "RHC": "Right-hand circuit",
    "RIF": "Reclearance in flight",
    "RIME": "Rime ",
    "RITE": "Right ",
    "RL": "Report leaving",
    "RLA": "Relay to",
    "RLCE": "Request level change en route",
    "RLLS": "Runway lead-in lighting system",
    "RLNA": "Request level not available",
    "RMK": "Remark",
    "RNAV": " Area navigation",
    "RNG": "Radio range",
    "RNP": "Required navigation performance",
    "ROBEX": "Regional OPMET bulletin exchange ",
    "ROC": "Rate of climb",
    "ROD": "Rate of descent",
    "RON": "Receiving only",
    "RPDS": "Reference path data selector",
    "RPI": "Radar position indicator",
    "RPL": "Repetitive flight plan",
    "RPLC": "Replace",
    "RPS": "Radar position symbol",
    "RPT*": "Repeat",
    "RQ*": "Request ",
    "RQMNTS": "Requirements",
    "RQP": "Request flight plan ",
    "RQS": "Request supplementary flight plan ",
    "RR": "Report reaching",
    "RRA": "",
    "RSC": "Rescue sub-centre",
    "RSCD": "Runway surface condition",
    "RSP": "Responder beacon",
    "RSR": "En-route surveillance radar",
    "RSS": "Root sum square",
    "RTD": "Delayed ",
    "RTE": "Route",
    "RTF": "Radiotelephone",
    "RTG": "Radiotelegraph",
    "RTHL": "Runway threshold light",
    "RTN": "Return",
    "RTODAH": "Rejected take-off distance available, helicopter",
    "RTS": "Return to service",
    "RTT": "Radioteletypewriter",
    "RTZL": "Runway touchdown zone light",
    "RUT": "Standard regional route transmitting frequencies",
    "RV": "Rescue vessel",
    "RVR": "Runway visual range",
    "RVSM": "Reduced vertical separation minimum  between FL 290 and FL 410",
    "RWY": "Runway",
    "S": "South",
    "S...": "State of the sea ",
    "SA": "Sand",
    "SALS": "Simple approach lighting system",
    "SAN": "Sanitary",
    "SAP": "As soon as possible",
    "SAR": "Search and rescue",
    "SARPS": "Standards and Recommended Practices [ICAO]",
    "SAT": "Saturday",
    "SATCOM": "Satellite communication",
    "SB": "Southbound",
    "SBAS": " Satellite-based augmentation system",
    "SC": "Stratocumulus",
    "SCT": "Scattered",
    "SD": "Standard deviation",
    "SDBY": "Stand by",
    "SDF": "Step down fix",
    "SE": "South-east",
    "SEA": "Sea ",
    "SEB": "South-eastbound",
    "SEC": "Seconds",
    "SECN": "Section",
    "SECT": "Sector",
    "SELCAL": "Selective calling system",
    "SEP": "September",
    "SER": "Service",
    "SEV": "Severe ",
    "SFC": "Surface",
    "SG": "Snow grains",
    "SGL": "Signal",
    "SH...": "Shower ",
    "SHF": "Super high frequency [3 000 to 30 000 MHz]",
    "SI": "International system of units",
    "SID": "Standard instrument departure",
    "SIF": "Selective identification feature",
    "SIG": "Significant",
    "SIGMET": "Information concerning en-route weather phenomena which may affect the safety of aircraft operations",
    "SIMUL": "Simultaneous",
    "SIWL": "Single isolated wheel load",
    "SKED": "Schedule",
    "SLP": "Speed limiting point",
    "SLW": "Slow",
    "SMC": "Surface movement control",
    "SMR": "Surface movement radar",
    "SN": "Snow",
    "SNOCLO": "Aerodrome closed due to snow ",
    "SNOWTAM": "Special series NOTAM notifying the presence",
    "SOC": "Start of climb",
    "SPECI": "Aerodrome special meteorological report ",
    "SPECIAL": "Local special meteorological report ",
    "SPI": "Special position indicator",
    "SPL": "Supplementary flight plan ",
    "SPOC": "SAR point of contact",
    "SPOT": "Spot wind",
    "SQ": "Squall",
    "SQL": "Squall line",
    "SR": "Sunrise",
    "SRA": "Surveillance radar approach",
    "SRE": "Surveillance radar element of precision approach radar system",
    "SRG": "Short range",
    "SRR": "Search and rescue region",
    "SRY": "Secondary",
    "SS": "Sandstorm",
    "SS": "Sunset",
    "SSB": "Single sideband",
    "SSE": "South-south-east",
    "SSR": "Secondary surveillance radar",
    "SST": "Supersonic transport",
    "SSW": "South-south-west",
    "ST": "Stratus",
    "STA": "Straight-in approach",
    "STAR": "Standard instrument arrival",
    "STD": "Standard",
    "STF": "Stratiform",
    "STN": "Station",
    "STNR": "Stationary",
    "STOL": "Short take-off and landing",
    "STS": "Status",
    "STWL": "Stopway light",
    "SUBJ": "Subject to",
    "SUN": "Sunday",
    "SUP": "Supplement ",
    "SUPPS": "Regional supplementary procedures",
    "SVC": "Service message",
    "SVCBL": "Serviceable",
    "SW": "South-west",
    "SWB": "South-westbound",
    "SWY": "Stopway",
    "T": "Temperature",
    "...T": "True ",
    "TA": "Traffic advisory",
    "TA": "Transition altitude",
    "TAA": "Terminal arrival altitude",
    "TACAN": "UHF tactical air navigation aid",
    "TAF": "Aerodrome forecast ",
    "TA/H": "Turn at an altitude/height",
    "TAIL": "Tail wind",
    "TAR": "Terminal area surveillance radar",
    "TAS": "True airspeed",
    "TAX": "Taxiing",
    "TC": "Tropical cyclone",
    "TCAC": "Tropical cyclone advisory centre",
    "TCAS": "RA             Traffic alert and collision avoidance system resolution advisory",
    "TCH": "Threshold crossing height",
    "TCU": "Towering cumulus",
    "TDO": "Tornado",
    "TDZ": "Touchdown zone",
    "TECR": "Technical reason",
    "TEL": "Telephone",
    "TEMPO": "Temporary",
    "TF": "Track to fix",
    "TFC": "Traffic",
    "TGL": "Touch-and-go landing",
    "TGS": "Taxiing guidance system",
    "THR": "Threshold",
    "THRU": "Through",
    "THU": "Thursday",
    "TIBA": "Traffic information broadcast by aircraft",
    "TIL": "Until",
    "TIP": "Until past . . . ",
    "TKOF": "Take-off",
    "TL...": "Till ",
    "TLOF": "Touchdown and lift-off area",
    "TMA": "Terminal control area",
    "TN...": "Minimum temperature ",
    "TNA": "Turn altitude",
    "TNH": "Turn height",
    "TO...": "To . . . ",
    "TOC": "Top of climb",
    "TODA": "Take-off distance available",
    "TODAH": "Take-off distance available, helicopter",
    "TOP": "Cloud top",
    "TORA": "Take-off run available",
    "TOX": "Toxic",
    "TP": "Turning point",
    "TR": "Track",
    "TRA": "Temporary reserved airspace",
    "TRANS": "Transmits",
    "TREND": "Trend forecast",
    "TRL": "Transition level",
    "TROP": "Tropopause",
    "TS": "Thunderstorm ",
    "TS...": "Thunderstorm ",
    "TSUNAMI": "Tsunami ",
    "TT": "Teletypewriter",
    "TUE": "Tuesday",
    "TURB": "Turbulence",
    "T-VASIS": " T visual approach slope indicator system",
    "TVOR": "Terminal VOR",
    "TWR": "Aerodrome control tower",
    "TWY": "Taxiway",
    "TWYL": "Taxiway-link",
    "TX...": "Maximum temperature ",
    "TXT*": "Text ",
    "TYP": "Type of aircraft",
    "TYPH": "Typhoon",
    "U": "Upward ",
    "UA": "Unmanned aircraft",
    "UAB...": "Until advised by . . .",
    "UAC": "Upper area control centre",
    "UAR": "Upper air route",
    "UAS": "Unmanned aircraft system",
    "UDF": "Ultra high frequency direction-finding station",
    "UFN": "Until further notice",
    "UHDT": "Unable higher due traffic",
    "UHF": "Ultra high frequency [300 to 3 000 MHz]",
    "UIC": "Upper information centre",
    "UIR": "Upper flight information region",
    "ULR": "Ultra long range",
    "UNA": "Unable",
    "UNAP": "Unable to approve",
    "UNL": "Unlimited",
    "UNREL": "Unreliable",
    "UP": "Unidentified precipitation ",
    "U/S": "Unserviceable",
    "UTA": "Upper control area",
    "UTC": "Coordinated Universal Time",
    "...V...": "Variations from the mean wind direction ",
    "VA": "Heading to an altitude",
    "VA": "Volcanic ash",
    "VAAC": "Volcanic ash advisory centre",
    "VAC...": "Visual approach chart ",
    "VAL": "In valleys",
    "VAN": "Runway control van",
    "VAR": "Magnetic variation",
    "VAR": "Visual-aural radio range",
    "VASIS": "Visual approach slope indicator systems",
    "VC...": "Vicinity of the aerodrome ",
    "VCY": "Vicinity",
    "VDF": "Very high frequency direction-finding station",
    "VER": "Vertical",
    "VFR": "Visual flight rules",
    "VHF": "Very high frequency [30 to 300 MHz]",
    "VI": "Heading to an intercept",
    "VIP": "Very important person",
    "VIS": "Visibility",
    "VLF": "Very low frequency [3 to 30 kHz]",
    "VLR": "Very long range",
    "VM": "Heading to a manual termination",
    "VMC": "Visual meteorological conditions",
    "VNAV": " Vertical navigation",
    "VOLMET": "Meteorological information for aircraft in flight",
    "VOR": "VHF omnidirectional radio range",
    "VORTAC": "VOR and TACAN combination",
    "VOT": "VOR airborne equipment test facility",
    "VPA": "Vertical path angle",
    "VPT": "Visual manoeuvre with prescribed track",
    "VRB": "Variable",
    "VSA": "By visual reference to the ground",
    "VSP": "Vertical speed",
    "VTF": "Vector to final",
    "VTOL": "Vertical take-off and landing",
    "VV...": "Vertical visibility ",
    "W": "West",
    "W": "White",
    "W...": "Sea-surface temperature ",
    "WAAS": "Wide area augmentation system",
    "WAC...": "World Aeronautical Chart — ICAO 1:1 000 000 ",
    "WAFC": "World area forecast centre",
    "WB": "Westbound",
    "WBAR": "Wing bar lights",
    "WDI": "Wind direction indicator",
    "WDSPR": "Widespread",
    "WED": "Wednesday",
    "WEF": "With effect from",
    "WGS-84": "World Geodetic System — 1984",
    "WI": "Within",
    "WID": "Width",
    "WIE": "With immediate effect",
    "WILCO": "Will comply",
    "WIND": "Wind",
    "WIP": "Work in progress",
    "WKN": "Weaken",
    "WNW": "West-north-west",
    "WO": "Without",
    "WPT": "Way-point",
    "WRNG": "Warning",
    "WS": "Wind shear",
    "WSPD": "Wind speed",
    "WSW": "West-south-west",
    "WT": "Weight",
    "WTSPT": "Waterspout",
    "WWW": "Worldwide web",
    "WX": "Weather",
    "X": "Cross",
    "XBAR": "Crossbar ",
    "XNG": "Crossing",
    "XS": "Atmospherics",
    "Y": "Yellow",
    "YCZ": "Yellow caution zone ",
    "YES*": "Yes ",
    "YR": "Your",
    "Z": "Coordinated Universal Time ",
}

entities = {
    "AA" : "MINIMUM ALTITUDE",
    "AC" : "CLASS B, C, D OR E SURFACE AREA (ICAO-CONTROL ZONE)",
    "AD" : "ADIZ",
    "AE" : "CONTROL AREA",
    "AF" : "FLIGHT INFORMATION REGION (FIR)",
    "AG" : "GENERAL FACILITY",
    "AH" : "UPPER CONTROL AREA",
    "AL" : "MINIMUM USABLE FLIGHT LEVEL",
    "AN" : "AIR NAVIGATION ROUTE",
    "AO" : "OCEANIC CONTROL ZONE (OCA)",
    "AP" : "REPORTING POINT",
    "AR" : "ATS ROUTE",
    "AT" : "TERMINAL CONTROL AREA (TMA)",
    "AU" : "UPPER FLIGHT INFORMATION REGION",
    "AV" : "UPPER ADVISORY AREA",
    "AX" : "INTERSECTION",
    "AZ" : "AERODROME TRAFFIC ZONE (ATZ)",
    "CA" : "AIR/GROUND FACILITY",
    "CB" : "AUTOMATIC DEPENDENT SURVEILLANCE - BROADCAST",
    "CC" : "AUTOMATIC DEPENDENT SURVEILLANCE - CONTRACT",
    "CD" : "CONTROLLER-PILOT DATA LINK COMMUNICATIONS",
    "CE" : "ENROUTE SURVELLENCE RADAR",
    "CG" : "GROUND CONTROLLED APPROACH SYSTEM (GCA)",
    "CL" : "SELECTIVE CALLING SYSTEM",
    "CM" : "SURFACE MOVEMENT RADAR",
    "CP" : "PAR",
    "CR" : "SURVEILLANCE RADAR ELEMENT OF PAR SYSTEM",
    "CS" : "SECONDARY SURVEILLANCE RADAR",
    "CT" : "TERMINAL AREA SURVEILLANCE RADAR",
    "FA" : "AERODROME",
    "FB" : "BRAKING ACTION MEASUREMENT EQUIPMENT",
    "FC" : "CEILING MEASUREMENT EQUIPMENT",
    "FD" : "DOCKING SYSTEM",
    "FE" : "OXYGEN",
    "FF" : "FIRE FIGHTING AND RESCUE",
    "FG" : "GROUND MOVEMENT CONTROL",
    "FH" : "HELICOPTER ALIGHTING AREA/PLATFORM",
    "FI" : "AIRCRAFT DE-ICING",
    "FJ" : "OILS",
    "FL" : "LANDING DIRECTION INDICATOR",
    "FM" : "METEOROLOGICAL SERVICE",
    "FO" : "FOG DISPERSAL SYSTEM",
    "FP" : "HELIPORT",
    "FS" : "SNOW REMOVAL EQUIPMENT",
    "FT" : "TRANSMISSOMETER",
    "FU" : "FUEL AVAILABILITY",
    "FW" : "WIND DIRECTION INDICATOR",
    "FZ" : "CUSTOMS",
    "GB" : "OPTICAL LANDING SYSTEM",
    "GC" : "TRANSIENT MAINTENANCE",
    "GD" : "STARTER UNIT",
    "GE" : "SOAP",
    "GF" : "DEMINERALIZED WATER",
    "GG" : "OXYGEN",
    "GH" : "OIL",
    "GI" : "DRAG CHUTES",
    "GJ" : "ASR",
    "GK" : "PRECISION APPROACH LANDING SYSTEM",
    "GL" : "FACSFAC",
    "GM" : "FIRING RANGE",
    "GN" : "NIGHT VISION GOGGLE (NVG) OPERATIONS",
    "GO" : "WARNING AREA",
    "GP" : "ARRESTING GEAR MARKERS (AGM)",
    "GQ" : "PULSATING/STEADY VISUAL APPROACH SLOPE INDICATOR",
    "GR" : "DIVERSE DEPARTURE",
    "GS" : "NITROGEN",
    "GT" : "IFR TAKE-OFF MINIMUMS AND DEPARTURE PROCEDURES",
    "GU" : "DE-ICE",
    "GV" : "CLEAR ZONE",
    "GX" : "RUNWAY DISTANCE REMAINING (RDR) SIGNS",
    "GY" : "HELO PAD",
    "GZ" : "BASE OPERATIONS",
    "IC" : "ILS",
    "ID" : "DME ASSOCIATED WITH ILS",
    "IG" : "GLIDE PATH (ILS)",
    "II" : "INNER MARKER (ILS)",
    "IL" : "LOCALIZER (ILS)",
    "IM" : "MIDDLE MARKER (ILS)",
    "IN" : "LOCALIZER",
    "IO" : "OUTER MARKER (ILS)",
    "IS" : "ILS CATEGORY I",
    "IT" : "ILS CATEGORY II",
    "IU" : "ILS CATEGORY III",
    "IW" : "MLS",
    "IX" : "LOCATOR, OUTER, (ILS)",
    "IY" : "LOCATOR, MIDDLE (ILS)",
    "LA" : "APPROACH LIGHTING SYSTEM",
    "LB" : "AERODROME BEACON",
    "LC" : "RUNWAY CENTERLINE LIGHTS",
    "LD" : "LANDING DIRECTION INDICATOR LIGHTS",
    "LE" : "RUNWAY EDGE LIGHTS",
    "LF" : "SEQUENCED FLASHING LIGHTS",
    "LG" : "PILOT-CONTROLLED LIGHTING",
    "LH" : "HIGH INTENSITY RUNWAY LIGHTS",
    "LI" : "RUNWAY END IDENTIFIER LIGHTS",
    "LJ" : "RUNWAY ALIGNMENT INDICATOR LIGHTS",
    "LK" : "CATEGORY II COMPONENTS OF APPROACH LIGHTING SYSTEM",
    "LL" : "LOW INTENSITY RUNWAY LIGHTS",
    "LM" : "MEDIUM INTENSITY RUNWAY LIGHTS",
    "LP" : "PRECISION APPROACH PATH INDICATOR",
    "LR" : "ALL LANDING AREA LIGHTING FACILITIES",
    "LS" : "STOPWAY LIGHTS",
    "LT" : "THRESHOLD LIGHTS",
    "LU" : "HELICOPTER APPROACH PATH INDICATOR",
    "LV" : "VISUAL APRROACH SLOPE INDICATOR",
    "LW" : "HELIPORT LIGHTING",
    "LX" : "TAXIWAY CENTER LINE LIGHTS",
    "LY" : "TAXIWAY EDGE LIGHTS",
    "LZ" : "RUNWAY TOUCH DOWN ZONE LIGHTS",
    "MA" : "MOVEMENT AREA",
    "MB" : "BEARING STRENGTH",
    "MC" : "CLEARWAY",
    "MD" : "DECLARED DISTANCES",
    "MG" : "TAXIING GUIDANCE SYSTEM",
    "MH" : "RUNWAY ARRESTING GEAR",
    "MK" : "PARKING AREA",
    "MM" : "DAYLIGHT MARKINGS",
    "MN" : "APRON",
    "MO" : "STOP BAR",
    "MP" : "AIRCRAFT STANDS",
    "MR" : "RUNWAY",
    "MS" : "STOPWAY",
    "MT" : "THRESHOLD",
    "MU" : "RUNWAY TURNING BAY",
    "MW" : "STRIP",
    "MX" : "TAXIWAY",
    "MY" : "RAPID EXIT TAXIWAY",
    "NA" : "ALL RADIO NAVIGATION FACILITIES",
    "NB" : "NDB",
    "NC" : "DECCA",
    "ND" : "DME",
    "NF" : "FAN MARKER",
    "NL" : "LOCATOR",
    "NM" : "VOR/DME",
    "NN" : "TACAN",
    "NT" : "VORTAC",
    "NV" : "VOR",
    "NX" : "DIRECTION FINDING STATION",
    "OA" : "AERONAUTICAL INFORMATION SERVICE",
    "OB" : "OBSTACLE",
    "OE" : "AIRCRAFT ENTRY REQUIREMENTS",
    "OL" : "OBSTACLE LIGHTS",
    "OR" : "RESCUE COORDINATION CENTER",
    "PA" : "STANDARD INSTRUMENT ARRIVAL (STAR)",
    "PB" : "STANDARD VFR ARRIVAL",
    "PC" : "CONTINGENCY PROCEDURES",
    "PD" : "STANDARD INSTRUMENT DEPARTURE (SID)",
    "PE" : "STANDARD VFR DEPARTURE",
    "PF" : "FLOW CONTROL PROCEDURES",
    "PH" : "HOLDING PROCEDURES",
    "PI" : "INSTRUMENT APPROACH PROCEDURE",
    "PK" : "VFR APPROACH PROCEDURE",
    "PL" : "OBSTACLE CLEARANCE LIMIT",
    "PM" : "AERODROME OPERATING MINIMA",
    "PN" : "NOISE OPERATING RESTRICTIONS",
    "PO" : "OBSTACLE CLEARANCE ALTITUDE",
    "PP" : "OBSTACLE CLEARANCE HEIGHT",
    "PR" : "RADIO FAILURE PROCEDURE",
    "PT" : "TRANSITION ALTITUDE",
    "PU" : "MISSED APPROACH PROCEDURE",
    "PX" : "MINIMUM HOLDING ALTITUDE",
    "PZ" : "ADIZ PROCEDURE",
    "RA" : "AIRSPACE RESERVATION",
    "RD" : "DANGER AREA",
    "RM" : 
    "RO : OVERFLYING OF",
    "RP" : "PROHIBITED AREA",
    "RR" : "RESTRICTED AREA",
    "RT" : "TEMPORARY RESTRICTED AREA",
    "SA" : "AUTOMATIC TERMINAL INFORMATION SERVICE (ATIS)",
    "SB" : "ATS REPORT OFFICE",
    "SC" : "AREA CONTROL CENTER",
    "SE" : "FLIGHT INFORMATION SERVICE",
    "SF" : "AERODROME FLIGHT INFORMATION SERVICE (AFIS)",
    "SL" : "FLOW CONTROL CENTER",
    "SO" : "OCEANIC AREA CONTROL CENTER",
    "SP" : "APPROACH CONTROL",
    "SS" : "FLIGHT SERVICE STATION",
    "ST" : "AERODROME CONTROL TOWER",
    "SU" : "UPPER AREA CONTROL CENTER",
    "SV" : "VOLMENT BROADCAST",
    "SY" : "UPPER ADVISORY SERVICE",
    "TT" : "MIJI",
    "WA" : "AIR DISPLAY",
    "WB" : "AEROBATICS",
    "WC" : "CAPTIVE BALLOON OR KITE",
    "WD" : "DEMOLITION OF EXPLOSIVES",
    "WE" : "EXERCISES",
    "WF" : "AIR REFUELING",
    "WG" : "GLIDER FLYING",
    "WH" : "BLASTING",
    "WJ" : "BANNER/TARGET TOWING",
    "WL" : "ASCENT OF FREE BALLOON",
    "WM" : "MISSLE, GUN OR ROCKET FIRING",
    "WP" : "PARACHUTE JUMPING EXERCISE",
    "WR" : "RADIOACTIVE MATERIALS OR TOXIC CHEMICALS",
    "WS" : "BURNING OR BLOWING GAS",
    "WT" : "MASS MOVEMENT OF ACFT",
    "WU" : "UNMANNED AIRCRAFT",
    "WV" : "FORMATION FLT",
    "WW" : "SIGNIFICANT VOLCANIC ACTIVITY",
    "WY" : "AERIAL SURVEY",
    "WZ" : "MODEL FLYING",
    "XX" : "OTHERS",
}

entities_cat = {
    "AA" : "AIRSPACE ORGANIZATION",
    "AC" : "AIRSPACE ORGANIZATION",
    "AD" : "AIRSPACE ORGANIZATION",
    "AE" : "AIRSPACE ORGANIZATION",
    "AF" : "AIRSPACE ORGANIZATION",
    "AG" : "AIRSPACE ORGANIZATION",
    "AH" : "AIRSPACE ORGANIZATION",
    "AL" : "AIRSPACE ORGANIZATION",
    "AN" : "AIRSPACE ORGANIZATION",
    "AO" : "AIRSPACE ORGANIZATION",
    "AP" : "AIRSPACE ORGANIZATION",
    "AR" : "AIRSPACE ORGANIZATION",
    "AT" : "AIRSPACE ORGANIZATION",
    "AU" : "AIRSPACE ORGANIZATION",
    "AV" : "AIRSPACE ORGANIZATION",
    "AX" : "AIRSPACE ORGANIZATION",
    "AZ" : "AIRSPACE ORGANIZATION",
    "CA" : "COMMUNICATIONS AND RADAR",
    "CB" : "COMMUNICATIONS AND RADAR",
    "CC" : "COMMUNICATIONS AND RADAR",
    "CD" : "COMMUNICATIONS AND RADAR",
    "CE" : "COMMUNICATIONS AND RADAR",
    "CG" : "COMMUNICATIONS AND RADAR",
    "CL" : "COMMUNICATIONS AND RADAR",
    "CM" : "COMMUNICATIONS AND RADAR",
    "CP" : "COMMUNICATIONS AND RADAR",
    "CR" : "COMMUNICATIONS AND RADAR",
    "CS" : "COMMUNICATIONS AND RADAR",
    "CT" : "COMMUNICATIONS AND RADAR",
    "FA" : "FACILITIES AND SERVICES",
    "FB" : "FACILITIES AND SERVICES",
    "FC" : "FACILITIES AND SERVICES",
    "FD" : "FACILITIES AND SERVICES",
    "FE" : "FACILITIES AND SERVICES",
    "FF" : "FACILITIES AND SERVICES",
    "FG" : "FACILITIES AND SERVICES",
    "FH" : "FACILITIES AND SERVICES",
    "FI" : "FACILITIES AND SERVICES",
    "FJ" : "FACILITIES AND SERVICES",
    "FL" : "FACILITIES AND SERVICES",
    "FM" : "FACILITIES AND SERVICES",
    "FO" : "FACILITIES AND SERVICES",
    "FP" : "FACILITIES AND SERVICES",
    "FS" : "FACILITIES AND SERVICES",
    "FT" : "FACILITIES AND SERVICES",
    "FU" : "FACILITIES AND SERVICES",
    "FW" : "FACILITIES AND SERVICES",
    "FZ" : "FACILITIES AND SERVICES",
    "GB" : "MILITARY",
    "GC" : "MILITARY",
    "GD" : "MILITARY",
    "GE" : "MILITARY",
    "GF" : "MILITARY",
    "GG" : "MILITARY",
    "GH" : "MILITARY",
    "GI" : "MILITARY",
    "GJ" : "MILITARY",
    "GK" : "MILITARY",
    "GL" : "MILITARY",
    "GM" : "MILITARY",
    "GN" : "MILITARY",
    "GO" : "MILITARY",
    "GP" : "MILITARY",
    "GQ" : "MILITARY",
    "GR" : "MILITARY",
    "GS" : "MILITARY",
    "GT" : "MILITARY",
    "GU" : "MILITARY",
    "GV" : "MILITARY",
    "GX" : "MILITARY",
    "GY" : "MILITARY",
    "GZ" : "MILITARY",
    "IC" : "INSTRUMENT AND MICROWAVE LANDING",
    "ID" : "INSTRUMENT AND MICROWAVE LANDING",
    "IG" : "INSTRUMENT AND MICROWAVE LANDING",
    "II" : "INSTRUMENT AND MICROWAVE LANDING",
    "IL" : "INSTRUMENT AND MICROWAVE LANDING",
    "IM" : "INSTRUMENT AND MICROWAVE LANDING",
    "IN" : "INSTRUMENT AND MICROWAVE LANDING",
    "IO" : "INSTRUMENT AND MICROWAVE LANDING",
    "IS" : "INSTRUMENT AND MICROWAVE LANDING",
    "IT" : "INSTRUMENT AND MICROWAVE LANDING",
    "IU" : "INSTRUMENT AND MICROWAVE LANDING",
    "IW" : "INSTRUMENT AND MICROWAVE LANDING",
    "IX" : "INSTRUMENT AND MICROWAVE LANDING",
    "IY" : "INSTRUMENT AND MICROWAVE LANDING",
    "LA" : "LIGHTNING",
    "LB" : "LIGHTNING",
    "LC" : "LIGHTNING",
    "LD" : "LIGHTNING",
    "LE" : "LIGHTNING",
    "LF" : "LIGHTNING",
    "LG" : "LIGHTNING",
    "LH" : "LIGHTNING",
    "LI" : "LIGHTNING",
    "LJ" : "LIGHTNING",
    "LK" : "LIGHTNING",
    "LL" : "LIGHTNING",
    "LM" : "LIGHTNING",
    "LP" : "LIGHTNING",
    "LR" : "LIGHTNING",
    "LS" : "LIGHTNING",
    "LT" : "LIGHTNING",
    "LU" : "LIGHTNING",
    "LV" : "LIGHTNING",
    "LW" : "LIGHTNING",
    "LX" : "LIGHTNING",
    "LY" : "LIGHTNING",
    "LZ" : "LIGHTNING",
    "MA" : "RAPID EXIT TAXYWAY",
    "MB" : "RAPID EXIT TAXYWAY",
    "MC" : "RAPID EXIT TAXYWAY",
    "MD" : "RAPID EXIT TAXYWAY",
    "MG" : "RAPID EXIT TAXYWAY",
    "MH" : "RAPID EXIT TAXYWAY",
    "MK" : "RAPID EXIT TAXYWAY",
    "MM" : "RAPID EXIT TAXYWAY",
    "MN" : "RAPID EXIT TAXYWAY",
    "MO" : "RAPID EXIT TAXYWAY",
    "MP" : "RAPID EXIT TAXYWAY",
    "MR" : "RAPID EXIT TAXYWAY",
    "MS" : "RAPID EXIT TAXYWAY",
    "MT" : "RAPID EXIT TAXYWAY",
    "MU" : "RAPID EXIT TAXYWAY",
    "MW" : "RAPID EXIT TAXYWAY",
    "MX" : "RAPID EXIT TAXYWAY",
    "MY" : "RAPID EXIT TAXYWAY",
    "NA" : "TERMINAL EN ROUTE NAVIGATION",
    "NB" : "TERMINAL EN ROUTE NAVIGATION",
    "NC" : "TERMINAL EN ROUTE NAVIGATION",
    "ND" : "TERMINAL EN ROUTE NAVIGATION",
    "NF" : "TERMINAL EN ROUTE NAVIGATION",
    "NL" : "TERMINAL EN ROUTE NAVIGATION",
    "NM" : "TERMINAL EN ROUTE NAVIGATION",
    "NN" : "TERMINAL EN ROUTE NAVIGATION",
    "NT" : "TERMINAL EN ROUTE NAVIGATION",
    "NV" : "TERMINAL EN ROUTE NAVIGATION",
    "NX" : "TERMINAL EN ROUTE NAVIGATION",
    "OA" : "OTHER INFORMATION",
    "OB" : "OTHER INFORMATION",
    "OE" : "OTHER INFORMATION",
    "OL" : "OTHER INFORMATION",
    "OR" : "OTHER INFORMATION",
    "PA" : "AIR TRAFFIC PROCEDURES",
    "PB" : "AIR TRAFFIC PROCEDURES",
    "PC" : "AIR TRAFFIC PROCEDURES",
    "PD" : "AIR TRAFFIC PROCEDURES",
    "PE" : "AIR TRAFFIC PROCEDURES",
    "PF" : "AIR TRAFFIC PROCEDURES",
    "PH" : "AIR TRAFFIC PROCEDURES",
    "PI" : "AIR TRAFFIC PROCEDURES",
    "PK" : "AIR TRAFFIC PROCEDURES",
    "PL" : "AIR TRAFFIC PROCEDURES",
    "PM" : "AIR TRAFFIC PROCEDURES",
    "PN" : "AIR TRAFFIC PROCEDURES",
    "PO" : "AIR TRAFFIC PROCEDURES",
    "PP" : "AIR TRAFFIC PROCEDURES",
    "PR" : "AIR TRAFFIC PROCEDURES",
    "PT" : "AIR TRAFFIC PROCEDURES",
    "PU" : "AIR TRAFFIC PROCEDURES",
    "PX" : "AIR TRAFFIC PROCEDURES",
    "PZ" : "AIR TRAFFIC PROCEDURES",
    "RA" : "AIR SPACE RESTRICTIONS",
    "RD" : "AIR SPACE RESTRICTIONS",
    "RM" : "AIR SPACE RESTRICTIONS",
    "RO" : "AIR SPACE RESTRICTIONS",
    "RP" : "AIR SPACE RESTRICTIONS",
    "RR" : "AIR SPACE RESTRICTIONS",
    "RT" : "AIR SPACE RESTRICTIONS",
    "SA" : "AIR TRAFFIC AND VOLMET SERVICES",
    "SB" : "AIR TRAFFIC AND VOLMET SERVICES",
    "SC" : "AIR TRAFFIC AND VOLMET SERVICES",
    "SE" : "AIR TRAFFIC AND VOLMET SERVICES",
    "SF" : "AIR TRAFFIC AND VOLMET SERVICES",
    "SL" : "AIR TRAFFIC AND VOLMET SERVICES",
    "SO" : "AIR TRAFFIC AND VOLMET SERVICES",
    "SP" : "AIR TRAFFIC AND VOLMET SERVICES",
    "SS" : "AIR TRAFFIC AND VOLMET SERVICES",
    "ST" : "AIR TRAFFIC AND VOLMET SERVICES",
    "SU" : "AIR TRAFFIC AND VOLMET SERVICES",
    "SV" : "AIR TRAFFIC AND VOLMET SERVICES",
    "SY" : "AIR TRAFFIC AND VOLMET SERVICES",
    "TT" : "HAZARD",
    "WA" : "WARNING",
    "WB" : "WARNING",
    "WC" : "WARNING",
    "WD" : "WARNING",
    "WE" : "WARNING",
    "WF" : "WARNING",
    "WG" : "WARNING",
    "WH" : "WARNING",
    "WJ" : "WARNING",
    "WL" : "WARNING",
    "WM" : "WARNING",
    "WP" : "WARNING",
    "WR" : "WARNING",
    "WS" : "WARNING",
    "WT" : "WARNING",
    "WU" : "WARNING",
    "WV" : "WARNING",
    "WW" : "WARNING",
    "WY" : "WARNING",
    "WZ" : "WARNING",
    "XX" : "OTHERS",
}

status = {
    "AC" :  "WITHDRAWN FOR MAINTENANCE",
    "AD" :  "AVAILABLE FOR DAYLIGHT OPERATIONS",
    "AF" :  "FLIGHT CHECKED AND FOUND RELIABLE",
    "AG" :  "OPERATING BUT GROUND CHECKED ONLY, AWAITING FLIGHT CHECK",
    "AH" :  "HOURS OF SERVICE ARE",
    "AK" :  "RESUMED NORMAL OPERATIONS",
    "AM" :  "MILITARY OPERATIONS ONLY",
    "AN" :  "AVAILABLE FOR NIGHT OPERATIONS",
    "AO" :  "OPERATIONAL",
    "AP" :  "PRIOR PERMISSION REQUIRED",
    "AQ" :  "COMPLETELY WITHDRAWN",
    "AR" :  "AVAILABLE, PRIOR PERMISSION REQUIRED",
    "AS" :  "UNSERVICEABLE",
    "AU" :  "NOT AVAILABLE",
    "AW" :  "COMPLETELY WITHDRAWN",
    "AX" :  "PREVIOUSLY PROMULGATED SHUTDOWN HAS BEEN CANCELLED",
    "CA" :  "ACTIVATED",
    "CC" :  "COMPLETED",
    "CD" :  "DEACTIVATED",
    "CE" :  "ERECTED",
    "CF" :  "FREQUENCY CHANGED TO",
    "CG" :  "DOWNGRADED TO",
    "CH" :  "CHANGED",
    "CI" :  "IDENTIFICATION OR RADIO CALL SIGN CHANGED TO",
    "CL" :  "REALIGNED",
    "CM" :  "DISPLACED",
    "CO" :  "OPERATING",
    "CP" :  "OPERATING ON REDUCED POWER",
    "CR" :  "TEMPORARILY REPLACED BY",
    "CS" :  "INSTALLED",
    "CT" :  "ON TEST, DO NOT USE",
    "GA" :  "NOT COINCIDENTAL WITH ILS/PAR",
    "GB" :  "IN RAISED POSITION",
    "GC" :  "TAIL HOOK ONLY",
    "GD" :  "OFFICIAL BUSINESS ONLY",
    "GE" :  "EXPECT LANDING DELAY",
    "GF" :  "EXTENSIVE SERVICE DELAY",
    "GG" :  "UNUSABLE BEYOND",
    "GH" :  "UNUSABLE",
    "GI" :  "UNMONITORED",
    "GJ" :  "IN PROGRESS",
    "GK" :  "MODERATE",
    "GL" :  "SEVERE",
    "GM" :  "NOT ILLUMINATED",
    "GN" :  "FREQUENCY NOT AVAILABLE",
    "GO" :  "IS WET",
    "GV" :  "NOT AUTHORIZED",
    "HA" :  "BRAKING ACTION IS",
    "HB" :  "BRAKING COEFFICIENT IS",
    "HC" :  "COVERED BY COMPACTED SNOW TO A DEPTH OF",
    "HD" :  "COVERED BY DRY SNOW TO A DEPTH OF",
    "HE" :  "COVERED BY WATER TO A DEPTH OF",
    "HF" :  "TOTALLY FREE OF SNOW AND ICE",
    "HG" :  "GRASS CUTTING IN PROGRESS",
    "HH" :  "HAZARD DUE TO",
    "HI" :  "COVERED BY ICE",
    "HJ" :  "LAUNCH PLANNED",
    "HK" :  "MIGRATION IN PROGRESS",
    "HL" :  "SNOW CLEARANCE COMPLETED",
    "HM" :  "MARKED BY",
    "HN" :  "COVERED BY WET SNOW OR SLUSH TO A DEPTH OF",
    "HO" :  "OBSCURED BY SNOW",
    "HP" :  "SNOW CLEARANCE IN PROGRESS",
    "HQ" :  "OPERATIONS CANCELLED",
    "HR" :  "STANDING WATER",
    "HS" :  "SANDING",
    "HT" :  "APPROACH ACCORDING TO SIGNAL AREA ONLY",
    "HU" :  "LAUNCH IN PROGRESS",
    "HV" :  "WORK COMPLETED",
    "HW" :  "WORK IN PROGRESS",
    "HX" :  "CONCENTRATION OF BIRDS",
    "HY" :  "SNOW BANKS EXIST",
    "HZ" :  "COVERED BY FROZEN RUTS AND RIDGES",
    "KK" :  "Volcanic Activity",
    "LA" :  "OPERATING ON AUXILIARY POWER SUPPLY",
    "LB" :  "RESERVED FOR AIRCRAFT BASED THEREIN",
    "LC" :  "CLOSED",
    "LD" :  "UNSAFE",
    "LE" :  "OPERATING WITHOUT AUXILIARY POWER SUPPLY",
    "LF" :  "INTERFERENCE FROM",
    "LG" :  "OPERATING WITHOUT IDENTIFICATION",
    "LH" :  "UNSERVICEABLE FOR AIRCRAFT HEAVIER THAN",
    "LI" :  "CLOSED TO IFR OPERATIONS",
    "LK" :  "OPERATING AS A FIXED LIGHT",
    "LL" :  "USABLE FOR LENGTH OF AND WIDTH OF",
    "LN" :  "CLOSED TO ALL NIGHT OPERATIONS",
    "LP" :  "PROHIBITED TO",
    "LR" :  "AIRCRAFT RESTRICTED TO RUNWAYS AND TAXIWAYS",
    "LS" :  "SUBJECT TO INTERRUPTION",
    "LT" :  "LIMITED TO",
    "LV" :  "CLOSED TO VFR OPERATIONS",
    "LW" :  "WILL TAKE PLACE",
    "LX" :  "OPERATING BUT CAUTION ADVISED DUE TO",
    "LY" :  "EFFECTIVE",
    "TT" :  "HAZARD",
    "XX" :  "OTHERS"
}

status_cat = {
    "AC" :  "AVAILABILITY",
    "AD" :  "AVAILABILITY",
    "AF" :  "AVAILABILITY",
    "AG" :  "AVAILABILITY",
    "AH" :  "AVAILABILITY",
    "AK" :  "AVAILABILITY",
    "AM" :  "AVAILABILITY",
    "AN" :  "AVAILABILITY",
    "AO" :  "AVAILABILITY",
    "AP" :  "AVAILABILITY",
    "AQ" :  "AVAILABILITY",
    "AR" :  "AVAILABILITY",
    "AS" :  "AVAILABILITY",
    "AU" :  "AVAILABILITY",
    "AW" :  "AVAILABILITY",
    "AX" :  "AVAILABILITY",
    "CA" :  "CHANGE",
    "CC" :  "CHANGE",
    "CD" :  "CHANGE",
    "CE" :  "CHANGE",
    "CF" :  "CHANGE",
    "CG" :  "CHANGE",
    "CH" :  "CHANGE",
    "CI" :  "CHANGE",
    "CL" :  "CHANGE",
    "CM" :  "CHANGE",
    "CO" :  "CHANGE",
    "CP" :  "CHANGE",
    "CR" :  "CHANGE",
    "CS" :  "CHANGE",
    "CT" :  "CHANGE",
    "GA" :  "MILITARY",
    "GB" :  "MILITARY",
    "GC" :  "MILITARY",
    "GD" :  "MILITARY",
    "GE" :  "MILITARY",
    "GF" :  "MILITARY",
    "GG" :  "MILITARY",
    "GH" :  "MILITARY",
    "GI" :  "MILITARY",
    "GJ" :  "MILITARY",
    "GK" :  "MILITARY",
    "GL" :  "MILITARY",
    "GM" :  "MILITARY",
    "GN" :  "MILITARY",
    "GO" :  "MILITARY",
    "GV" :  "MILITARY",
    "HA" :  "HAZARD",
    "HB" :  "HAZARD",
    "HC" :  "HAZARD",
    "HD" :  "HAZARD",
    "HE" :  "HAZARD",
    "HF" :  "HAZARD",
    "HG" :  "HAZARD",
    "HH" :  "HAZARD",
    "HI" :  "HAZARD",
    "HJ" :  "HAZARD",
    "HK" :  "HAZARD",
    "HL" :  "HAZARD",
    "HM" :  "HAZARD",
    "HN" :  "HAZARD",
    "HO" :  "HAZARD",
    "HP" :  "HAZARD",
    "HQ" :  "HAZARD",
    "HR" :  "HAZARD",
    "HS" :  "HAZARD",
    "HT" :  "HAZARD",
    "HU" :  "HAZARD",
    "HV" :  "HAZARD",
    "HW" :  "HAZARD",
    "HX" :  "HAZARD",
    "HY" :  "HAZARD",
    "HZ" :  "HAZARD",
    "KK" :  "VOLCANIC ACTIVITY",
    "LA" :  "LIMITATION",
    "LB" :  "LIMITATION",
    "LC" :  "LIMITATION",
    "LD" :  "LIMITATION",
    "LE" :  "LIMITATION",
    "LF" :  "LIMITATION",
    "LG" :  "LIMITATION",
    "LH" :  "LIMITATION",
    "LI" :  "LIMITATION",
    "LK" :  "LIMITATION",
    "LL" :  "LIMITATION",
    "LN" :  "LIMITATION",
    "LP" :  "LIMITATION",
    "LR" :  "LIMITATION",
    "LS" :  "LIMITATION",
    "LT" :  "LIMITATION",
    "LV" :  "LIMITATION",
    "LW" :  "LIMITATION",
    "LX" :  "LIMITATION",
    "LY" :  "LIMITATION",
    "TT" :  "LIMITATION",
    "XX" :  "OTHERS"
}
